// Comprehensive TypeScript types for the church management system database

export interface Database {
  public: {
    Tables: {
      churches: {
        Row: {
          id: string;
          name: string;
          address: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          logo_url: string | null;
          theme_colors: any;
          default_language: string;
          timezone: string;
          settings: any;
          subscription_plan: string;
          subscription_expires_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          theme_colors?: any;
          default_language?: string;
          timezone?: string;
          settings?: any;
          subscription_plan?: string;
          subscription_expires_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          theme_colors?: any;
          default_language?: string;
          timezone?: string;
          settings?: any;
          subscription_plan?: string;
          subscription_expires_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      roles: {
        Row: {
          id: string;
          church_id: string;
          name: string;
          display_name: string;
          description: string | null;
          is_default: boolean;
          permissions: any;
          color: string;
          sort_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          name: string;
          display_name: string;
          description?: string | null;
          is_default?: boolean;
          permissions?: any;
          color?: string;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          name?: string;
          display_name?: string;
          description?: string | null;
          is_default?: boolean;
          permissions?: any;
          color?: string;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          church_id: string;
          email: string;
          full_name: string;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          birthday: string | null;
          birthday_month: number | null;
          birthday_day: number | null;
          address: string | null;
          emergency_contact: any | null;
          profile_photo_url: string | null;
          language: string;
          timezone: string | null;
          is_confirmed: boolean;
          is_active: boolean;
          last_login_at: string | null;
          last_seen_at: string | null;
          church_joined_at: string;
          notes: string | null;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          email: string;
          full_name: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          birthday?: string | null;
          birthday_month?: number | null;
          birthday_day?: number | null;
          address?: string | null;
          emergency_contact?: any | null;
          profile_photo_url?: string | null;
          language?: string;
          timezone?: string | null;
          is_confirmed?: boolean;
          is_active?: boolean;
          last_login_at?: string | null;
          last_seen_at?: string | null;
          church_joined_at?: string;
          notes?: string | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          email?: string;
          full_name?: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          birthday?: string | null;
          birthday_month?: number | null;
          birthday_day?: number | null;
          address?: string | null;
          emergency_contact?: any | null;
          profile_photo_url?: string | null;
          language?: string;
          timezone?: string | null;
          is_confirmed?: boolean;
          is_active?: boolean;
          last_login_at?: string | null;
          last_seen_at?: string | null;
          church_joined_at?: string;
          notes?: string | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role_id: string;
          assigned_by: string | null;
          assigned_at: string;
          expires_at: string | null;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          role_id: string;
          assigned_by?: string | null;
          assigned_at?: string;
          expires_at?: string | null;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          role_id?: string;
          assigned_by?: string | null;
          assigned_at?: string;
          expires_at?: string | null;
          is_active?: boolean;
        };
      };
      departments: {
        Row: {
          id: string;
          church_id: string;
          name: string;
          description: string | null;
          leader_id: string | null;
          parent_department_id: string | null;
          color: string;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          name: string;
          description?: string | null;
          leader_id?: string | null;
          parent_department_id?: string | null;
          color?: string;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          name?: string;
          description?: string | null;
          leader_id?: string | null;
          parent_department_id?: string | null;
          color?: string;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          church_id: string;
          title: string;
          description: string | null;
          assignee_id: string | null;
          assigner_id: string | null;
          department_id: string | null;
          due_date: string | null;
          priority: string;
          status: string;
          completion_percentage: number;
          estimated_hours: number | null;
          actual_hours: number | null;
          tags: string[] | null;
          attachments: any;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          title: string;
          description?: string | null;
          assignee_id?: string | null;
          assigner_id?: string | null;
          department_id?: string | null;
          due_date?: string | null;
          priority?: string;
          status?: string;
          completion_percentage?: number;
          estimated_hours?: number | null;
          actual_hours?: number | null;
          tags?: string[] | null;
          attachments?: any;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          title?: string;
          description?: string | null;
          assignee_id?: string | null;
          assigner_id?: string | null;
          department_id?: string | null;
          due_date?: string | null;
          priority?: string;
          status?: string;
          completion_percentage?: number;
          estimated_hours?: number | null;
          actual_hours?: number | null;
          tags?: string[] | null;
          attachments?: any;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          church_id: string;
          title: string;
          description: string | null;
          event_date: string;
          start_time: string | null;
          end_time: string | null;
          location: string | null;
          event_type: string;
          image_url: string | null;
          max_attendees: number | null;
          requires_registration: boolean;
          registration_deadline: string | null;
          is_recurring: boolean;
          recurrence_pattern: any | null;
          is_public: boolean;
          created_by: string | null;
          status: string;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          title: string;
          description?: string | null;
          event_date: string;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          event_type?: string;
          image_url?: string | null;
          max_attendees?: number | null;
          requires_registration?: boolean;
          registration_deadline?: string | null;
          is_recurring?: boolean;
          recurrence_pattern?: any | null;
          is_public?: boolean;
          created_by?: string | null;
          status?: string;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          title?: string;
          description?: string | null;
          event_date?: string;
          start_time?: string | null;
          end_time?: string | null;
          location?: string | null;
          event_type?: string;
          image_url?: string | null;
          max_attendees?: number | null;
          requires_registration?: boolean;
          registration_deadline?: string | null;
          is_recurring?: boolean;
          recurrence_pattern?: any | null;
          is_public?: boolean;
          created_by?: string | null;
          status?: string;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      attendance: {
        Row: {
          id: string;
          church_id: string;
          user_id: string;
          program_id: string | null;
          event_id: string | null;
          attendance_date: string;
          arrival_time: string | null;
          departure_time: string | null;
          was_present: boolean;
          attendance_type: string;
          notes: string | null;
          marked_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          user_id: string;
          program_id?: string | null;
          event_id?: string | null;
          attendance_date: string;
          arrival_time?: string | null;
          departure_time?: string | null;
          was_present?: boolean;
          attendance_type?: string;
          notes?: string | null;
          marked_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          user_id?: string;
          program_id?: string | null;
          event_id?: string | null;
          attendance_date?: string;
          arrival_time?: string | null;
          departure_time?: string | null;
          was_present?: boolean;
          attendance_type?: string;
          notes?: string | null;
          marked_by?: string | null;
          created_at?: string;
        };
      };
      prayer_requests: {
        Row: {
          id: string;
          church_id: string;
          title: string | null;
          message: string;
          submitted_by: string | null;
          is_anonymous: boolean;
          is_urgent: boolean;
          status: string;
          prayer_count: number;
          category: string | null;
          visibility: string;
          answered_at: string | null;
          answer_testimony: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          title?: string | null;
          message: string;
          submitted_by?: string | null;
          is_anonymous?: boolean;
          is_urgent?: boolean;
          status?: string;
          prayer_count?: number;
          category?: string | null;
          visibility?: string;
          answered_at?: string | null;
          answer_testimony?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          title?: string | null;
          message?: string;
          submitted_by?: string | null;
          is_anonymous?: boolean;
          is_urgent?: boolean;
          status?: string;
          prayer_count?: number;
          category?: string | null;
          visibility?: string;
          answered_at?: string | null;
          answer_testimony?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      announcements: {
        Row: {
          id: string;
          church_id: string;
          title: string;
          content: string;
          announcement_type: string;
          priority: string;
          target_audience: any;
          requires_acknowledgment: boolean;
          is_blinking: boolean;
          publish_at: string;
          expires_at: string | null;
          image_url: string | null;
          created_by: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          title: string;
          content: string;
          announcement_type?: string;
          priority?: string;
          target_audience?: any;
          requires_acknowledgment?: boolean;
          is_blinking?: boolean;
          publish_at?: string;
          expires_at?: string | null;
          image_url?: string | null;
          created_by?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          title?: string;
          content?: string;
          announcement_type?: string;
          priority?: string;
          target_audience?: any;
          requires_acknowledgment?: boolean;
          is_blinking?: boolean;
          publish_at?: string;
          expires_at?: string | null;
          image_url?: string | null;
          created_by?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          church_id: string;
          user_id: string;
          title: string;
          message: string;
          notification_type: string;
          related_entity_type: string | null;
          related_entity_id: string | null;
          action_url: string | null;
          is_read: boolean;
          is_push_sent: boolean;
          is_email_sent: boolean;
          priority: string;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          user_id: string;
          title: string;
          message: string;
          notification_type: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          is_push_sent?: boolean;
          is_email_sent?: boolean;
          priority?: string;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          notification_type?: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          is_push_sent?: boolean;
          is_email_sent?: boolean;
          priority?: string;
          read_at?: string | null;
          created_at?: string;
        };
      };
      financial_records: {
        Row: {
          id: string;
          church_id: string;
          transaction_type: string;
          amount: number;
          currency: string;
          description: string;
          category: string | null;
          subcategory: string | null;
          transaction_date: string;
          payment_method: string | null;
          reference_number: string | null;
          receipt_url: string | null;
          recorded_by: string | null;
          approved_by: string | null;
          status: string;
          tags: string[] | null;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          church_id: string;
          transaction_type: string;
          amount: number;
          currency?: string;
          description: string;
          category?: string | null;
          subcategory?: string | null;
          transaction_date: string;
          payment_method?: string | null;
          reference_number?: string | null;
          receipt_url?: string | null;
          recorded_by?: string | null;
          approved_by?: string | null;
          status?: string;
          tags?: string[] | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          church_id?: string;
          transaction_type?: string;
          amount?: number;
          currency?: string;
          description?: string;
          category?: string | null;
          subcategory?: string | null;
          transaction_date?: string;
          payment_method?: string | null;
          reference_number?: string | null;
          receipt_url?: string | null;
          recorded_by?: string | null;
          approved_by?: string | null;
          status?: string;
          tags?: string[] | null;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_upcoming_birthdays: {
        Args: {
          church_uuid: string;
          days_ahead: number;
        };
        Returns: {
          id: string;
          full_name: string;
          birthday_month: number;
          birthday_day: number;
          days_until_birthday: number;
        }[];
      };
      user_has_permission: {
        Args: {
          permission_name: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}